import { ADAPTERS, CAPABILITY_MATRIX } from "./adapters";
import { CanonicalVisualSpec, CreativeIntent, CreativeIntentSchema, PromptIssue, PromptPlan, VariationStrategy, VisualCompilation } from "./contracts";

export function buildCanonicalVisualSpec(intent: CreativeIntent): CanonicalVisualSpec {
  return { subject:{description:intent.subject,action:intent.narrative||"still, intentional presence",appearance:intent.mandatoryElements.join(", ")},environment:{description:intent.environment||"environment to be resolved",materials:[],spatialComposition:"clear foreground, subject and background separation"},direction:{concept:intent.emotionalIntent||intent.objective,style:"editorial, deliberate, brand-coherent",realism:"highly believable",brandCodes:intent.mandatoryElements},camera:{shot:intent.assetType==="video"?"cinematic medium-wide shot":"editorial medium shot",angle:"eye level",lens:"natural perspective",movement:intent.assetType==="video"?"slow controlled tracking":"none"},lighting:{source:"motivated natural light",direction:"side-lit",quality:"soft with controlled contrast",contrast:"medium"},composition:{hierarchy:"single clear focal point",negativeSpace:"intentional breathing room",depth:"layered",textZone:intent.usage.includes("social")?"reserved safe area":"none"},rendering:{finish:intent.qualityTarget,texture:"natural material detail",color:"coherent restrained palette",avoidArtifacts:["distorted anatomy","warped geometry","unintended text"]},temporal:intent.assetType==="video"?{opening:intent.environment,action:intent.narrative||intent.subject,ending:"resolved hero frame",duration:intent.duration}:undefined,invariants:intent.preservationConstraints,forbidden:intent.forbiddenElements,references:intent.references };
}
export function validateVisualIntent(intent: CreativeIntent): PromptIssue[] {
  const issues:PromptIssue[]=[];
  if(!intent.environment) issues.push({code:"missing_environment",severity:"warning",message:"Environment is not specified."});
  if(intent.references.some(r=>!r.role.trim())) issues.push({code:"reference_without_role",severity:"error",message:"Every reference needs a role."});
  if(intent.assetType==="video"&&!intent.duration) issues.push({code:"missing_duration",severity:"warning",message:"Video duration defaults to 8 seconds."});
  for(const generator of intent.generators){const c=CAPABILITY_MATRIX[generator]; if(intent.assetType==="video"&&!c.video)issues.push({code:`${generator}_no_video`,severity:"error",message:`${generator} does not support video in this profile.`}); if(intent.assetType==="image-edit"&&!c.edit)issues.push({code:`${generator}_no_edit`,severity:"error",message:`${generator} does not support precise editing in this profile.`}); if(!c.supportedRatios.includes(intent.aspectRatio))issues.push({code:`${generator}_ratio`,severity:"error",message:`${intent.aspectRatio} is not supported by ${generator}.`}); if(intent.references.length>c.maxReferences)issues.push({code:`${generator}_references`,severity:"warning",message:`${generator} accepts at most ${c.maxReferences} references; reduce or prioritize them.`}); if(generator==="sora"&&intent.duration&&(intent.duration>c.maxDuration!))issues.push({code:"sora_duration",severity:"error",message:`Sora profile maximum duration is ${c.maxDuration}s.`}); }
  const contradictions=intent.mandatoryElements.filter(x=>intent.forbiddenElements.includes(x)); if(contradictions.length)issues.push({code:"contradiction",severity:"error",message:`Required and forbidden: ${contradictions.join(", ")}.`});
  return issues;
}
function plan(intent:CreativeIntent,strategy:VariationStrategy="balanced"):PromptPlan{return{preserve:intent.preservationConstraints,reinforce:[intent.subject,intent.objective],simplify:intent.references.filter(r=>r.importance<0.4).map(r=>r.role),ambiguities:intent.environment?[]:["environment"],adaptations:[],variationStrategy:strategy};}
export function compileVisualPrompts(raw:unknown,strategy:VariationStrategy="balanced"):VisualCompilation { const intent=CreativeIntentSchema.parse(raw); const spec=buildCanonicalVisualSpec(intent); const issues=validateVisualIntent(intent); const promptPlan=plan(intent,strategy); const prompts=intent.generators.map(g=>ADAPTERS[g].compile(intent,spec,promptPlan,issues.filter(x=>x.code.startsWith(g)||!x.code.includes("_no_")&&!x.code.includes("_ratio")))); return {intent,spec,prompts,comparison:prompts.map(p=>({generator:p.generator,fit:p.score.generatorFit,limitations:p.issues.filter(i=>i.severity==="error").map(i=>i.message),adaptations:p.explanation}))}; }
export function createControlledVariant(compilation:VisualCompilation,generator:typeof compilation.prompts[number]["generator"],strategy:VariationStrategy){const original=compilation.prompts.find(p=>p.generator===generator);if(!original)throw new Error("Generator was not compiled");const nextSpec=structuredClone(compilation.spec);if(strategy==="lighting-only")nextSpec.lighting.quality="hard directional light with graphic shadows";if(strategy==="camera-only")nextSpec.camera.angle="low three-quarter angle";if(strategy==="composition-only")nextSpec.composition.hierarchy="asymmetric editorial composition";if(strategy==="motion-only"&&nextSpec.temporal)nextSpec.camera.movement="slow arc around the subject";const nextPlan={...original.plan,variationStrategy:strategy};return {...ADAPTERS[generator].compile(compilation.intent,nextSpec,nextPlan,original.issues,original.version+1),parentId:original.id};}
