import Link from "next/link";
import CommandIcon from "@/components/CommandIcon";

const TRACKS = [["Identité & marque",100,"brain"],["Site web",78,"website"],["Contenus & réseaux",64,"content"],["Produits & ressources",52,"library"],["Système & automatisations",86,"sparkles"]] as const;
const TASKS = [["Finaliser la homepage","En cours","Site web","bg-[#dfeac2]"],["Valider le guide client","À relire","Orbit Critic","bg-[#f9d9e6]"],["Préparer la vidéo fondatrice","À créer","Contenu","bg-[#dcecff]"],["Vérifier la liste d’attente","Prêt","Système","bg-[#f5df75]"]] as const;
const CONTENT = [["Teasing 24March OS","Post Instagram","18 juil."],["Studio Life #3","Reel / coulisses","20 juil."],["Guide client","Carousel Instagram","22 juil."],["Pourquoi 24March","TikTok / Reel","24 juil."]] as const;
const PAGES = [["Accueil",88],["À propos",72],["Journal",42],["Contact",30],["Mentions légales",20]] as const;

export default function LaunchPage() {
  return <div className="space-y-4 pb-8">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><span className="command-label"><CommandIcon name="launch" className="h-3.5 w-3.5" /> Opération lancement</span><h1 className="mt-2 text-3xl font-black tracking-[-0.04em] sm:text-4xl">Lancement 24March Studio</h1><p className="mt-1 text-sm font-medium text-black/48">Une seule vue pour savoir ce qui est prêt, bloqué et prioritaire.</p></div><Link href="/projects/new" className="command-button self-start"><CommandIcon name="plus" className="h-4 w-4" /> Ajouter un projet</Link></header>
    <section className="grid min-w-0 gap-3 lg:grid-cols-[1.15fr_0.85fr]"><article className="relative min-w-0 overflow-hidden rounded-[24px] border border-black/10 bg-[linear-gradient(135deg,#fbf6e8,#edf2e5)] p-4 sm:p-5"><div className="absolute -right-16 -top-16 h-48 w-48 rounded-full border-[28px] border-[#c3d995]/30" /><div className="relative"><p className="command-label">Compte à rebours</p><div className="mt-3 flex items-end gap-3"><span className="text-6xl font-black tracking-[-0.07em] sm:text-8xl">47</span><span className="mb-2 text-sm font-black uppercase leading-tight">jours<br />restants</span></div><p className="mt-2 text-sm font-black uppercase tracking-[0.08em] text-[#7d9f4c]">1er septembre 2026</p><div className="mt-5"><div className="flex justify-between text-[10px] font-black uppercase tracking-[0.1em]"><span>Progression globale</span><span>76%</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-black/7"><div className="h-full w-[76%] rounded-full bg-[#98b85f]" /></div></div></div></article><article className="command-card min-w-0 p-4 sm:p-5"><p className="command-label">Prochaine meilleure action</p><h2 className="mt-2 text-2xl font-black tracking-[-0.04em]">Terminer ce qui débloque le reste.</h2><p className="mt-2 text-sm font-medium leading-relaxed text-black/48">La homepage et le guide client conditionnent la communication, la liste d’attente et le contenu de lancement.</p><a href="#tasks" className="mt-4 block rounded-[18px] bg-[#f5df75]/70 p-4"><p className="text-sm font-black">Voir les tâches critiques</p><p className="mt-1 text-xs font-medium text-black/55">Accéder directement à ce qui reste à fermer.</p></a></article></section>
    <section id="roadmap" className="scroll-mt-24 grid min-w-0 gap-3 xl:grid-cols-[0.9fr_1.1fr]"><article className="command-card min-w-0 p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><div><p className="command-label">Roadmap</p><h2 className="mt-1 text-xl font-black">Progression par chantier</h2></div><span className="command-pill bg-[#e6edcd]">5 chantiers</span></div><div className="mt-4 space-y-4">{TRACKS.map(([label,value,icon]) => <div key={label} className="grid min-w-0 grid-cols-[34px_1fr_auto] items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-[11px] bg-[#edf2e5]"><CommandIcon name={icon} className="h-4 w-4" /></span><div className="min-w-0"><p className="truncate text-sm font-black">{label}</p><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-black/7"><div className="h-full rounded-full bg-[#9dbd61]" style={{ width: `${value}%` }} /></div></div><span className="text-xs font-black">{value}%</span></div>)}</div></article><article id="tasks" className="command-card min-w-0 scroll-mt-24 p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><div><p className="command-label">Tâches critiques</p><h2 className="mt-1 text-xl font-black">Ce qui reste à fermer</h2></div><span className="command-pill bg-[#f9d9e6]">4 tâches</span></div><div className="mt-4 space-y-2.5">{TASKS.map(([title,status,tag,color]) => <div key={title} className="flex min-w-0 items-center gap-3 rounded-[18px] border border-black/8 bg-white/70 p-3"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-[14px] ${color}`}><CommandIcon name="check" className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{title}</p><p className="mt-0.5 text-[11px] font-medium text-black/45">{tag}</p></div><span className="shrink-0 rounded-full border border-black/8 bg-white px-2.5 py-1 text-[9px] font-black">{status}</span></div>)}</div></article></section>
    <section className="grid min-w-0 gap-3 xl:grid-cols-2"><article id="content" className="command-card min-w-0 scroll-mt-24 p-4 sm:p-5"><div><p className="command-label">Calendrier éditorial</p><h2 className="mt-1 text-xl font-black">Contenus à créer et publier</h2></div><div className="mt-4 divide-y divide-black/8">{CONTENT.map(([title,type,date],index)=><div key={title} className="grid grid-cols-[44px_1fr_auto] items-center gap-3 py-3"><div className={`h-11 rounded-[12px] ${index%2===0?"bg-[#e6d3b5]":"bg-[#dcecff]"}`} /><div className="min-w-0"><p className="truncate text-sm font-black">{title}</p><p className="text-[11px] text-black/45">{type}</p></div><span className="text-[10px] font-bold text-black/40">{date}</span></div>)}</div></article><article id="site" className="command-card min-w-0 scroll-mt-24 p-4 sm:p-5"><div><p className="command-label">Production du site</p><h2 className="mt-1 text-xl font-black">Pages à terminer</h2></div><div className="mt-4 space-y-3">{PAGES.map(([label,value])=><div key={label} className="grid grid-cols-[1fr_auto] items-center gap-3"><div><div className="flex justify-between text-sm font-black"><span>{label}</span></div><div className="mt-2 h-2 rounded-full bg-black/7"><div className="h-full rounded-full bg-[#9dbd61]" style={{ width: `${value}%` }} /></div></div><span className="text-xs font-black">{value}%</span></div>)}</div></article></section>
  </div>;
}
